application: swang-ui
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /web
  static_dir: web
    
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: home.app
  
- url: /foobar
  script: foobar.app
  
- url: /editor
  script: editor.app

libraries:
- name: webapp2
  version: "2.5.1"
